#!/bin/bash

packages=(
  "auto_route"
  "cached_network_image"
  "chat_gpt_sdk"
  "cloud_firestore"
  "cloud_functions"
  "cupertino_icons"
  "dio"
  "firebase_auth"
  "firebase_core"
  "firebase_crashlytics"
  "firebase_messaging"
  "firebase_remote_config"
  "firebase_storage"
  "flutter_app_badger"
  "flutter_flavor"
  "flutter_flavorizr"
  "flutter_hooks"
  "flutter_image_compress"
  "flutter_local_notifications"
  "flutter_markdown"
  "flutter_markdown_latex"
  "flutter_native_timezone"
  "flutter_svg"
  "fluttertoast"
  "font_awesome_flutter"
  "freezed_annotation"
  "get"
  "gpt_markdown"
  "google_sign_in"
  "hooks_riverpod"
  "http"
  "image"
  "image_cropper"
  "image_gallery_saver"
  "image_picker"
  "in_app_purchase"
  "in_app_purchase_android"
  "in_app_purchase_storekit"
  "in_app_review"
  "intl"
  "markdown"
  "material_floating_search_bar_2"
  "path_provider"
  "pull_to_refresh"
  "retrofit"
  "riverpod_annotation"
  "shared_preferences"
  "sign_in_with_apple"
  "timezone"
  "url_launcher"
  "uuid"
  "gpt_markdown"
)

echo "Adding packages to dependencies..."

# Loop through each package and add it as a dev dependency
for package_name in "${packages[@]}"; do
  echo "Adding ${package_name}..."
  flutter pub add "${package_name}"
done

echo "All specified packages have been added."