enum EnvKeys {
  AWS_S3_ACCESS_KEY,
  AWS_S3_BOOKMARK_CATEGORY_IMAGES_BUCKET,
  AWS_S3_POST_IMAGES_BUCKET,
  AWS_S3_SECRET_KEY,
  AWS_S3_USER_IMAGES_BUCKET,
  OFFICIAL_ACCOUNT_UID,
  OPEN_AI_API_KEY,
  VERIFY_ANDROID_ENDPOINT,
  VERIFY_IOS_ENDPOINT,
  WOLFRAM_APP_ID
}
