
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/consts/env_keys.dart"
    - "lib/infrastructure/firestore/mocks/mock_q_doc.dart"
    - "lib/infrastructure/firestore/mocks/mock_doc.dart"
    - "lib/infrastructure/model/database_schema/common/moderated_image/moderation_label/moderation_label.dart"
    - "lib/infrastructure/model/rest_api/verify_purchase/response/ios_receipt_response/ios_receipt_response.dart"
    - "lib/infrastructure/model/rest_api/verify_purchase/response/ios_receipt_response/pending_renewal_info/pending_renewal_info.dart"
    - "lib/model/rest_api/open_ai/generate_text/generate_text_response/generate_text_request.dart"
    - "test/infrastructure/repository/auth_repository_test.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_const_constructors: true # dart fix --applyで実行