
include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/consts/env_keys.dart"
    - "lib/infrastructure/firestore/mocks/mock_q_doc.dart"
    - "lib/infrastructure/firestore/mocks/mock_doc.dart"
    - "lib/model/moderation_label/moderation_label.dart"
    - "lib/model/receipt_response/ios_receipt_response/ios_receipt_response.dart"
  errors:
    invalid_annotation_target: ignore