
include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/l10n_en.dart"
    - "lib/l10n/l10n_ja.dart"
  errors:
    invalid_annotation_target: ignore