workflows:
  test-flight-ios-workflow:
    name: TestFlight iOS Workflow
    integrations:
      app_store_connect: great_talk_codemagic_key
    labels:
      - iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.firebaseapp.greatTalkDev
      vars:
        APP_ID: 1667705303
      flutter: v3.32.2
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release --flavor dev \
            --export-options-plist=/Users/builder/export_options.plist \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1))
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      # https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/bfcf910be8894ba63b875af6c942ac7e1dace526/integrations/firebase_crashlytics_demo_project/codemagic.yaml
      scripts:
        - name: Upload debug symbols to Firebase Crashlytics
          script: |
            echo "Find build artifacts"
            dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/Runner.xcarchive -name "*.dSYM" | head -1)
            if [[ -z ${dsymPath} ]]
            then
              echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
            else
              echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics"
              ls -d -- ios/Pods/*
              $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols \
                -p ios $dsymPath
            fi
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Developer