name: great_talk
description: A new Flutter project.

publish_to: 'none' 

version: 2.0.14+117

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  chat_gpt_sdk: ^2.2.4
  cloud_firestore: ^4.7.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  firebase_auth: ^4.7.2
  firebase_core: ^2.4.1
  flash: ^3.0.5+1
  flutter_app_badger: ^1.5.0
  flutter_dotenv: ^5.0.2
  flutter_flavor: ^3.1.1
  flutter_flavorizr: ^2.1.6
  flutter_hooks: ^0.20.0
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^15.1.0+1
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.1.2
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.4
  http: ^0.13.5
  image: ^4.0.17
  image_cropper: ^4.0.1
  image_picker: ^1.0.2
  in_app_review: ^2.0.6
  in_app_purchase: ^3.1.1
  in_app_purchase_android: ^0.3.0+11
  in_app_purchase_storekit: ^0.3.6+3
  intl: ^0.18.0
  material_floating_search_bar_2: ^0.5.0
  minio_new: ^1.0.2
  path_provider: ^2.1.0
  pull_to_refresh: ^2.0.0
  retrofit: ^4.0.1
  shared_preferences: ^2.0.16
  sign_in_with_apple: ^5.0.0
  timezone: ^0.9.2
  url_launcher: ^6.1.9
  uuid: ^3.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - dev.env
    - prod.env
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo2.png'
# Flavorの設定
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "すごいAI Dev"
      android:
        applicationId: "com.firebaseapp.great_talk_dev"
      ios:
        bundleId: "com.firebaseapp.greatTalkDev"
    verification:
      app:
        name: "すごいAI Verification"
      android:
        applicationId: "com.firebaseapp.great_talk_verification"
      ios:
        bundleId: "com.firebaseapp.greatTalkVerification"
    prod:
      app:
        name: "すごいAI"
      android:
        applicationId: "com.firebaseapp.great_talk"
      ios:
        bundleId: "com.firebaseapp.greatTalk"
