name: great_talk
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.8+42

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_chat_ui: ^1.6.4
  uuid: ^3.0.7
  flutter_hooks: ^0.18.5+1
  get: ^4.6.5
  firebase_core: ^2.4.1
  shared_preferences: ^2.0.16
  intl: ^0.17.0
  fluttertoast: ^8.1.2
  chat_gpt_flutter: ^0.0.1
  flutter_dotenv: ^5.0.2
  material_floating_search_bar: ^0.3.7
  flutter_flavor: ^3.1.1
  flutter_flavorizr: ^2.1.5
  firebase_auth: ^4.2.5
  in_app_purchase: ^3.1.1
  http: ^0.13.5
  cloud_firestore: ^4.3.2
  url_launcher: ^6.1.9
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.jpeg'
# Flavorの設定
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Great Talk Dev"
      android:
        applicationId: "com.firebaseapp.great_talk_dev"
      ios:
        bundleId: "com.firebaseapp.greatTalkDev"
    verification:
      app:
        name: "Great Talk Verification"
      android:
        applicationId: "com.firebaseapp.great_talk_verification"
      ios:
        bundleId: "com.firebaseapp.greatTalkVerification"
    prod:
      app:
        name: "Great Talk"
      android:
        applicationId: "com.firebaseapp.great_talk"
      ios:
        bundleId: "com.firebaseapp.greatTalk"
