name: great_talk
description: A new Flutter project.

publish_to: 'none' 
# lib/constants/remote_config_constants.dartのappVersionも変更
version: 6.0.22+239

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.8
  cloud_functions: ^5.5.1
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_messaging: ^15.2.6
  firebase_remote_config: ^5.4.4
  firebase_storage: ^12.4.6
  flutter_app_badger: ^1.5.0
  flutter_flavor: ^3.1.4
  flutter_flavorizr: ^2.4.1
  flutter_hooks: ^0.21.2
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.2.1
  flutter_native_timezone_latest: ^1.0.0
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  gpt_markdown: ^1.0.19
  google_sign_in: ^6.3.0
  hooks_riverpod: ^2.6.1
  http: ^1.4.0
  image: ^4.5.4
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+1
  in_app_purchase_storekit: ^0.4.0
  in_app_review: ^2.0.10
  intl: ^0.20.2
  markdown: ^7.3.0
  path_provider: ^2.1.5
  pull_to_refresh: ^2.0.0
  retrofit: ^4.4.2
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  timezone: ^0.10.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  test: ^1.25.15
  mockito: ^5.4.6
  fake_cloud_firestore: ^3.1.0
  fake_firebase_security_rules: ^0.5.3
  firebase_auth_mocks: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.2.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
dependency_overrides:
  analyzer: 7.3.0
  analyzer_plugin: 0.12.0
  custom_lint_visitor: 1.0.0+7.3.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.png'
# Flavorの設定
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "ShareAI Dev"
      android:
        applicationId: "com.firebaseapp.great_talk_dev"
      ios:
        bundleId: "com.firebaseapp.greatTalkDev"
    verification:
      app:
        name: "ShareAI Verification"
      android:
        applicationId: "com.firebaseapp.great_talk_verification"
      ios:
        bundleId: "com.firebaseapp.greatTalkVerification"
    prod:
      app:
        name: "ShareAI"
      android:
        applicationId: "com.firebaseapp.great_talk"
      ios:
        bundleId: "com.firebaseapp.greatTalk"
