name: great_talk
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.40+84

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_chat_ui: ^1.6.4
  uuid: ^3.0.7
  flutter_hooks: ^0.18.5+1
  get: ^4.6.5
  firebase_core: ^2.4.1
  shared_preferences: ^2.0.16
  intl: ^0.17.0
  fluttertoast: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_flavor: ^3.1.1
  flutter_flavorizr: ^2.1.6
  in_app_purchase: ^3.1.1
  http: ^0.13.5
  url_launcher: ^6.1.9
  google_fonts: ^4.0.3
  dio: ^5.0.1
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1
  cloud_firestore: ^4.7.0
  in_app_review: ^2.0.6
  image_picker: ^0.8.7
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^14.0.0+2
  flutter_native_timezone: ^2.0.0
  flutter_chat_types: ^3.6.0
  freezed_annotation: ^2.2.0
  in_app_purchase_storekit: ^0.3.6+3
  timezone: ^0.9.2
  in_app_purchase_android: ^0.2.5+4
  material_floating_search_bar_2: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - dev.env
    - prod.env
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo2.png'
# Flavorの設定
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "すごいAI Dev"
      android:
        applicationId: "com.firebaseapp.great_talk_dev"
      ios:
        bundleId: "com.firebaseapp.greatTalkDev"
    verification:
      app:
        name: "すごいAI Verification"
      android:
        applicationId: "com.firebaseapp.great_talk_verification"
      ios:
        bundleId: "com.firebaseapp.greatTalkVerification"
    prod:
      app:
        name: "すごいAI"
      android:
        applicationId: "com.firebaseapp.great_talk"
      ios:
        bundleId: "com.firebaseapp.greatTalk"
