name: "Install Flutter Dependencies"

description: "dependencies install step"

runs:
  using: "composite"
  steps:
    - name: "Setup Flutter"
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.32.2"
        cache: true